version: '3.9'

services:
  postgres:
    image: docker.io/postgres:17
    container_name: postgres
    ports:
      - "5432:5432" # Expose port 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
