options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 1800s

steps:
- name: rust:1.89
  id: build-and-test
  entrypoint: bash
  args:
    - -c
    - -exo
    - pipefail
    - |
      apt-get update
      apt-get install -y postgresql-client podman

      # Start Postgres container
      podman run -d \
        --name postgres \
        -e POSTGRES_USER=postgres \
        -e POSTGRES_PASSWORD=postgres \
        -e POSTGRES_DB=chronicle_test \
        -p 5432:5432 \
        docker.io/postgres:17-alpine

      # Wait for database
      until pg_isready -h localhost -p 5432 -U postgres; do
        echo "Waiting for Postgres..."
        sleep 1
      done

      cargo install sqlx-cli --no-default-features --features postgres
      export DATABASE_URL=postgres://postgres:postgres@localhost:5432/chronicle_test
      cd backend
      sqlx migrate run
      cargo test -- --test-threads=1