timeout: 3600s

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
- name: "gcr.io/cloud-builders/docker"
  id: build-image
  args:
    [
      "build",
      "-t", "$_IMAGE_URL:latest",
      "$_DIRECTORY"
    ]

- name: "gcr.io/cloud-builders/docker"
  id: push-image
  args:
    [
      "push",
      "$_IMAGE_URL:latest"
    ]