timeout: 3600s

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
- name: "gcr.io/cloud-builders/docker"
  id: build-image
  args:
    [
      "build",
      "-t", "$_IMAGE_URL:$COMMIT_SHA",
      "$_DIRECTORY"
    ]

- name: "gcr.io/cloud-builders/docker"
  id: tag-latest
  args:
    [
      "tag",
      "$_IMAGE_URL:$COMMIT_SHA",
      "$_IMAGE_URL:latest"
    ]

- name: "gcr.io/cloud-builders/docker"
  id: push-image-sha
  args:
    [
      "push",
      "$_IMAGE_URL:$COMMIT_SHA"
    ]

- name: "gcr.io/cloud-builders/docker"
  id: push-image-latest
  args:
    [
      "push",
      "$_IMAGE_URL:latest"
    ]

- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  id: deploy
  entrypoint: gcloud
  args:
    [
      "run", "deploy", "$_SERVICE_NAME",
      "--image", "$_IMAGE_URL:$COMMIT_SHA",
      "--region", "$_REGION",
      "--platform", "managed",
      "--quiet"
    ]
