port = 5000
allowed_origin = ["http://localhost:5173"]

[admin]
username = "test@example.com"
password = "test123"

[database]
host = "localhost"
name = "chronicle"
username = "chronicle"
password = "password"