name: Deploy to Vercel

on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dkershner6/vercel-set-env-action@v3
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: frontend
          envVariableKeys: PUBLIC_API_URL
        env:
          PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}
          TARGET_PUBLIC_API_URL: production
          TYPE_PUBLIC_API_URL: plain
          
      - uses: amondnet/vercel-action@v25
        with:
          vercel-project-name: chronicle
          working-directory: frontend
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod --confirm'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
